import { GameEvent } from "./types"

/**
 * 35 Highly realistic mock events centered around the University of Maryland (UMD)
 * to showcase Huddle's Hyperlocal Discovery capabilities to unauthenticated users.
 */
export const MOCK_EVENTS = [
  {
    id: "mock-event-0",
    name: "UMD Hackathon Brainstorm",
    category: "Learning",
    date: "2026-02-22",
    time: "13:00",
    location: "Iribe Center",
    geopoint: {
      latitude: 38.980831,
      longitude: -76.927244,
    },
    description: "Brainstorming session for the upcoming hackathon. Pizza will be provided!",
    currentPlayers: 6,
    maxPlayers: 12,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-1",
    name: "Pickup Basketball 5v5",
    category: "Sports",
    date: "2026-02-21",
    time: "17:30",
    location: "Eppley Recreation Center",
    geopoint: {
      latitude: 38.982080,
      longitude: -76.925043,
    },
    description: "Need 2 more for a full court run. Bringing my own ball.",
    currentPlayers: 7,
    maxPlayers: 15,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-2",
    name: "Late Night Study Session",
    category: "Learning",
    date: "2026-02-22",
    time: "18:30",
    location: "McKeldin Library",
    geopoint: {
      latitude: 38.980986,
      longitude: -76.934406,
    },
    description: "Grinding out CMSC 330 projects before the deadline.",
    currentPlayers: 5,
    maxPlayers: 26,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-3",
    name: "Terps Game Watch Party",
    category: "Community",
    date: "2026-02-21",
    time: "10:00",
    location: "Looney's Pub",
    geopoint: {
      latitude: 38.990194,
      longitude: -76.941246,
    },
    description: "Come watch the game with fellow Terps! Drink specials all night.",
    currentPlayers: 3,
    maxPlayers: 22,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-4",
    name: "Midnight Soccer",
    category: "Sports",
    date: "2026-02-23",
    time: "20:30",
    location: "Engineering Field",
    geopoint: {
      latitude: 38.990265,
      longitude: -76.939239,
    },
    description: "Casual 11v11 under the lights. All skill levels welcome.",
    currentPlayers: 7,
    maxPlayers: 17,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-5",
    name: "Smash Bros Tournament",
    category: "Gaming",
    date: "2026-02-21",
    time: "11:00",
    location: "Stamp Student Union",
    geopoint: {
      latitude: 38.988051,
      longitude: -76.933972,
    },
    description: "Weekly local. Bring your own controller if possible.",
    currentPlayers: 8,
    maxPlayers: 27,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-6",
    name: "Resume Review Workshop",
    category: "Learning",
    date: "2026-02-22",
    time: "10:00",
    location: "Career Center",
    geopoint: {
      latitude: 38.982504,
      longitude: -76.933777,
    },
    description: "Get your resume roasted by industry pros.",
    currentPlayers: 6,
    maxPlayers: 20,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-7",
    name: "Photography Walk",
    category: "Arts & Culture",
    date: "2026-02-22",
    time: "15:00",
    location: "McKeldin Mall",
    geopoint: {
      latitude: 38.989669,
      longitude: -76.931749,
    },
    description: "Golden hour photowalk around campus. Bring any camera!",
    currentPlayers: 5,
    maxPlayers: 27,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-8",
    name: "Acoustic Jam Session",
    category: "Music",
    date: "2026-02-21",
    time: "15:30",
    location: "Washington Quad",
    geopoint: {
      latitude: 38.981404,
      longitude: -76.938932,
    },
    description: "Bring your acoustic instruments and chill.",
    currentPlayers: 8,
    maxPlayers: 25,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: true,
  },
  {
    id: "mock-event-9",
    name: "Volleyball 6v6",
    category: "Sports",
    date: "2026-02-22",
    time: "17:00",
    location: "La Plata Beach",
    geopoint: {
      latitude: 38.990016,
      longitude: -76.939871,
    },
    description: "Sand volleyball by the dorms.",
    currentPlayers: 6,
    maxPlayers: 22,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-10",
    name: "Startup Pitch Practice",
    category: "Business",
    date: "2026-02-21",
    time: "11:30",
    location: "Startup Shell",
    geopoint: {
      latitude: 38.994812,
      longitude: -76.944851,
    },
    description: "Practice your 3-minute pitches for the upcoming competition.",
    currentPlayers: 4,
    maxPlayers: 18,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-11",
    name: "Yoga on the Mall",
    category: "Outdoors",
    date: "2026-02-21",
    time: "14:00",
    location: "McKeldin Mall",
    geopoint: {
      latitude: 38.994776,
      longitude: -76.936373,
    },
    description: "Morning flow. Bring a mat or just use the grass.",
    currentPlayers: 5,
    maxPlayers: 12,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-12",
    name: "Coffee & Code",
    category: "Learning",
    date: "2026-02-23",
    time: "18:00",
    location: "Casey's Coffee",
    geopoint: {
      latitude: 38.985405,
      longitude: -76.932395,
    },
    description: "Working on side projects and drinking way too much espresso.",
    currentPlayers: 7,
    maxPlayers: 13,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-13",
    name: "D&D One Shot",
    category: "Gaming",
    date: "2026-02-21",
    time: "13:00",
    location: "Board and Brew",
    geopoint: {
      latitude: 38.988916,
      longitude: -76.943223,
    },
    description: "Looking for 4 adventurers for a quick 3-hour dungeon crawl.",
    currentPlayers: 2,
    maxPlayers: 29,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: true,
  },
  {
    id: "mock-event-14",
    name: "Ultimate Frisbee Pickup",
    category: "Sports",
    date: "2026-02-22",
    time: "18:00",
    location: "Fraternity Row Field",
    geopoint: {
      latitude: 38.989268,
      longitude: -76.927536,
    },
    description: "Cleats recommended, we're playing pretty competitive today.",
    currentPlayers: 2,
    maxPlayers: 21,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-15",
    name: "Calculus 2 Group Tutoring",
    category: "Learning",
    date: "2026-02-21",
    time: "12:30",
    location: "Math Building",
    geopoint: {
      latitude: 38.980175,
      longitude: -76.927763,
    },
    description: "Going over integration by parts.",
    currentPlayers: 9,
    maxPlayers: 22,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-16",
    name: "Open Mic Night",
    category: "Music",
    date: "2026-02-21",
    time: "21:00",
    location: "TerpZone",
    geopoint: {
      latitude: 38.991417,
      longitude: -76.929509,
    },
    description: "Signups start at 7:30. Singers, comedians, poets welcome.",
    currentPlayers: 4,
    maxPlayers: 13,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-17",
    name: "Spikeball Tournament",
    category: "Sports",
    date: "2026-02-22",
    time: "20:30",
    location: "Engineering Field",
    geopoint: {
      latitude: 38.993654,
      longitude: -76.942064,
    },
    description: "Bracket style. Losers buy ice cream.",
    currentPlayers: 7,
    maxPlayers: 25,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: true,
  },
  {
    id: "mock-event-18",
    name: "Machine Learning Reading Group",
    category: "Learning",
    date: "2026-02-21",
    time: "16:30",
    location: "Iribe Center",
    geopoint: {
      latitude: 38.989184,
      longitude: -76.940424,
    },
    description: "Discussing the new Attention paper.",
    currentPlayers: 4,
    maxPlayers: 25,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-19",
    name: "Board Game Night",
    category: "Community",
    date: "2026-02-23",
    time: "21:30",
    location: "Stamp Student Union",
    geopoint: {
      latitude: 38.994099,
      longitude: -76.942881,
    },
    description: "Catan, Ticket to Ride, and more.",
    currentPlayers: 3,
    maxPlayers: 24,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-20",
    name: "Run Club: 5k Pace",
    category: "Outdoors",
    date: "2026-02-23",
    time: "16:30",
    location: "Xfinity Center",
    geopoint: {
      latitude: 38.994046,
      longitude: -76.933880,
    },
    description: "Easy 5k loop around campus.",
    currentPlayers: 9,
    maxPlayers: 17,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-21",
    name: "Thrifting Trip Group",
    category: "Community",
    date: "2026-02-21",
    time: "20:00",
    location: "Route 1",
    geopoint: {
      latitude: 38.981265,
      longitude: -76.941432,
    },
    description: "Walking down to the local thrift spots.",
    currentPlayers: 6,
    maxPlayers: 18,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: true,
  },
  {
    id: "mock-event-22",
    name: "Tennis Beginners",
    category: "Sports",
    date: "2026-02-21",
    time: "21:30",
    location: "Eppley Tennis Courts",
    geopoint: {
      latitude: 38.992354,
      longitude: -76.935615,
    },
    description: "Just hitting around, no pressure.",
    currentPlayers: 4,
    maxPlayers: 17,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-23",
    name: "Physics 161 Study Group",
    category: "Learning",
    date: "2026-02-21",
    time: "20:00",
    location: "Toll Physics Building",
    geopoint: {
      latitude: 38.984557,
      longitude: -76.938981,
    },
    description: "Reviewing kinematics.",
    currentPlayers: 8,
    maxPlayers: 27,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-24",
    name: "Meditation Circle",
    category: "Outdoors",
    date: "2026-02-22",
    time: "15:00",
    location: "Memorial Chapel Garden",
    geopoint: {
      latitude: 38.983334,
      longitude: -76.933693,
    },
    description: "Guided 20-minute mindfulness session.",
    currentPlayers: 3,
    maxPlayers: 12,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-25",
    name: "Flag Football",
    category: "Sports",
    date: "2026-02-23",
    time: "15:00",
    location: "Washington Quad",
    geopoint: {
      latitude: 38.985259,
      longitude: -76.942031,
    },
    description: "7v7 touch, flags provided.",
    currentPlayers: 6,
    maxPlayers: 25,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-26",
    name: "Debate Prep",
    category: "Learning",
    date: "2026-02-21",
    time: "15:30",
    location: "Skinner Building",
    geopoint: {
      latitude: 38.984074,
      longitude: -76.939714,
    },
    description: "Mock debate rounds.",
    currentPlayers: 3,
    maxPlayers: 18,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-27",
    name: "Food Truck Meetup",
    category: "Food & Drink",
    date: "2026-02-22",
    time: "15:30",
    location: "Lot 1",
    geopoint: {
      latitude: 38.983458,
      longitude: -76.933282,
    },
    description: "Grabbing tacos before class.",
    currentPlayers: 3,
    maxPlayers: 23,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-28",
    name: "Sketching at the Stamp",
    category: "Arts & Culture",
    date: "2026-02-23",
    time: "20:00",
    location: "Stamp Student Union",
    geopoint: {
      latitude: 38.982897,
      longitude: -76.934297,
    },
    description: "Life drawing practice.",
    currentPlayers: 5,
    maxPlayers: 25,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-29",
    name: "Pickleball Doubles",
    category: "Sports",
    date: "2026-02-23",
    time: "10:00",
    location: "Eppley Recreation Center",
    geopoint: {
      latitude: 38.984455,
      longitude: -76.926856,
    },
    description: "Winner stays on court.",
    currentPlayers: 4,
    maxPlayers: 24,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-30",
    name: "Blockchain Talk",
    category: "Learning",
    date: "2026-02-21",
    time: "16:00",
    location: "Van Munching Hall",
    geopoint: {
      latitude: 38.980716,
      longitude: -76.932687,
    },
    description: "Guest speaker on Web3.",
    currentPlayers: 2,
    maxPlayers: 14,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: true,
  },
  {
    id: "mock-event-31",
    name: "Dog Walking Pack",
    category: "Outdoors",
    date: "2026-02-23",
    time: "15:30",
    location: "Lake Artemesia",
    geopoint: {
      latitude: 38.988633,
      longitude: -76.938264,
    },
    description: "Bring your pups!",
    currentPlayers: 9,
    maxPlayers: 17,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-32",
    name: "C++ Debugging Help",
    category: "Learning",
    date: "2026-02-21",
    time: "12:30",
    location: "Iribe Ground Floor",
    geopoint: {
      latitude: 38.992902,
      longitude: -76.931338,
    },
    description: "I am losing my mind over segfaults. Help.",
    currentPlayers: 2,
    maxPlayers: 27,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: true,
  },
  {
    id: "mock-event-33",
    name: "Trivia Night",
    category: "Community",
    date: "2026-02-22",
    time: "20:00",
    location: "Looney's Pub",
    geopoint: {
      latitude: 38.985301,
      longitude: -76.937304,
    },
    description: "Forming a team of 6. Need a history buff!",
    currentPlayers: 7,
    maxPlayers: 18,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  },
  {
    id: "mock-event-34",
    name: "Sunrise Cycling",
    category: "Outdoors",
    date: "2026-02-23",
    time: "15:00",
    location: "Paint Branch Trail",
    geopoint: {
      latitude: 38.982137,
      longitude: -76.931769,
    },
    description: "15-mile ride out and back.",
    currentPlayers: 7,
    maxPlayers: 12,
    createdBy: "mock-user",
    organizerName: "UMD Community",
    isBoosted: false,
  }
];
